"""apikey-torrentitem

Revision ID: df288f2cf1fa
Revises: 
Create Date: 2024-09-20 20:37:08.652142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df288f2cf1fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('never_expire', sa.Boolean(), nullable=False),
    sa.Column('expiration_date', sa.BigInteger(), nullable=True),
    sa.Column('latest_query_date', sa.BigInteger(), nullable=True),
    sa.Column('total_queries', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_api_key'), 'api_keys', ['api_key'], unique=True)
    op.create_table('torrent_items',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('raw_title', sa.String(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('magnet', sa.String(), nullable=True),
    sa.Column('info_hash', sa.String(length=40), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('seeders', sa.Integer(), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('indexer', sa.String(), nullable=False),
    sa.Column('privacy', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('torrent_download', sa.String(), nullable=True),
    sa.Column('trackers', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('file_index', sa.Integer(), nullable=True),
    sa.Column('full_index', sa.JSON(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_torrent_items_info_hash'), 'torrent_items', ['info_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_torrent_items_info_hash'), table_name='torrent_items')
    op.drop_table('torrent_items')
    op.drop_index(op.f('ix_api_keys_api_key'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
