"""Initial migration

Revision ID: 847b9f591666
Revises: 
Create Date: 2024-09-20 13:03:24.196751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847b9f591666'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('never_expire', sa.Boolean(), nullable=False),
    sa.Column('expiration_date', sa.BigInteger(), nullable=True),
    sa.Column('latest_query_date', sa.BigInteger(), nullable=True),
    sa.Column('total_queries', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_api_key'), 'api_keys', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_keys_api_key'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
