version: "3.8"

services:

  stream-fusion:
    image: ghcr.io/limedrive/stream-fusion:develop
    container_name: stream-fusion
    environment:
      SECRET_API_KEY: 'superkey_that_can_be_changed'
      TMDB_API_KEY: 'REDATED'
      FLARESOLVERR_HOST: flaresolverr
      JACKETT_HOST: jackett
      JACKETT_API_KEY: 'REDACTED'
      ZILEAN_URL: 'http://zilean:8181'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LOG_LEVEL: DEBUG
      LOG_REDACTED: False
      TZ: Europe/London
    ports:
      - 8080:8080
    volumes:
      - ./stream-fusion:/app/config
    depends_on:
      - redis
      - zilean
      - jackett
      - flaresolverr
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    volumes:
      - ./redis:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  zilean:
    image: ipromknight/zilean:latest
    container_name: zilean
    restart: unless-stopped
    expose:
      - 8181
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - ./zilean_data:/app/data
    environment:
      - Zilean__ElasticSearch__Url=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy


  elasticsearch:
    image: elasticsearch:8.14.3@sha256:1ddbb1ae0754278f3ab53edc24fcc5c790ebc2422cc47abea760b24abee2d88a
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      ES_SETTING_DISCOVERY_TYPE: single-node
      ES_SETTING_XPACK_SECURITY_ENABLED: false
      ES_SETTING_BOOTSTRAP_MEMORY__LOCK: true
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    expose:
      - 9200
    deploy:
      resources:
        limits:
          memory: 2g
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 | grep -q 'You Know, for Search'"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - elastic_data:/usr/share/elasticsearch/data:rw

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    expose:
      - 8191
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./jackett:/config
      - ./blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

volumes:
  elastic_data: